theGardn/theGardnStore

server/db/models/user.js
=> Database #UserModel - created User model

server/db/models/order.js
=> Database #Order-Model - created Order Model

server/db/models/orderDetails.js, server/db/models/product.js
=> CreateDatabse #productdb product.js order_details.js "prettify"

server/api/index.js, server/api/products.js
=> Routes #route-api/product - created /api/products GET route

.travis.yml, server/db/models/user.js, server/db/models/user.spec.js
=> Travis deploy

.travis.yml, server/db/models/user.spec.js
=> Travis test

client/store/products.js
=> Products reducer

client/store/user.js
=> REDUX #productdb -modify items to localStorage, added checkoutThunk

.babelrc, package-lock.json, package.json, webpack.config.js
=> WEBPACK #ant-d-test - get master working again

.babelrc, client/components/simple-card.js, client/store/user.spec.js, package-lock.json, package.json, webpack.config.js
=> Router fix - user

package-lock.json, package.json, public/index.html
=> REACTBOOTSTRAP #components -- added CDN and installed React-bootstrap

client/store/products.js
=> REDUX #reducer -- fixed products reducer

client/app.js, client/components/auth-form.js, client/components/components-style/navbar.css, client/components/navbar.js, client/components/user-home.js, client/routes.js, package-lock.json, package.json
=> NAVBAR #user-home - basic bootstrapy navbar with working links and auth

client/components/productDetail.js, client/components/singleProductCard.js
=> COMPONENT #PengComponent -create productDetail, singleProductCard draft

client/components/components-style/navbar.css, client/components/navbar.js, client/components/order-detail-sidebar.js, client/store/user.js
=> NAVBAR #user-home - added some styling and logo to navbar ORDER DETAILS -- created basic order details sidebar

client/app.js, client/components/components-style/app.css, client/components/components-style/navbar.css, client/components/navbar.js
=> NAVBAR #navbar -- fixed positioning and added cart icon link

client/app.js, client/components/navbar.js
=> NAVBAR APPJS #navbar -- fixed merge issues

client/components/productDetail.js, client/components/singleProductCard.js, client/store/user.js
=> 'REDUX #PengComponent -bugfixing'

client/components/cart/cart-card.js, client/components/cart/cart-container.js, client/components/components-style/cart.css, client/store/user.js, server/api/cart.js
=> Cart functions - created cart change qty function

client/components/orderHistory.js, client/components/orderHistoryCard.js
=> COMPONENT #PengComponent -create orderHistory

client/components/user-home.spec.js
=> removed unnecessary test

client/components/orderHistory.js, client/routes.js, client/store/user.js
=> DEBUG #PengComponent -debug and add route for orderhistory

client/components/orderHistory.js, client/components/orderHistoryCard.js, client/components/productDetail.js, client/components/singleProductCard.js, client/routes.js, client/store/products.js, client/store/user.js
=> DEBUG #PengComponent -debug for singleProduct

client/components/cart/cart-container.js
=> Removed Dummy Data #CartUpdates - removed dummy data from cart

client/components/cart/cart-container.js, client/components/order-detail-sidebar.js, client/store/user.js
=> CART #cart-persist - fixed local storage to store items correctly

client/components/index.js, client/components/navbar.js
=> added conditional history nav bar link

client/store/user.js, server/api/users.js
=> DEBUG #PengComponent -userApi storeApi

client/store/user.js
=> USER REDUX #cart-persist - working on cart persistance

client/components/index.js, client/components/orderHistory.js, client/components/orderHistoryCard.js, client/components/singleProductCard.js, client/routes.js, client/store/user.js, public/style.css
=> DEBUG #PengComponent -fix style and display for sP and oH

public/style.css
=> DEBUG #PengComponent -style css for oH adjust screen

client/components/singleProductCard.js, public/style.css
=> DEBUG #PengComponent -singleProduct back button and margin by screen

client/components/cart/cart-card.js, client/components/order-detail-sidebar.js, client/store/user.js, server/api/cart.js, server/api/users.js
=> #FixCartDelete - fixed cart delete + updating the quantity

client/components/singleProductCard.js, client/store/user.js
=> #SingleProduct-Cart fixed issue of adding same cart twice

client/components/singleProductCard.js
=> Fix single product add - was adding qty was string

client/components/checkout-page.js, client/components/purchaseInfo.js, client/routes.js, client/store/user.js, server/api/checkout.js
=> COMPONENT #PengComponent -purchaseConfirm page
